# Generated by Django 4.2.5 on 2023-10-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zonework", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="date",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
