# Generated by Django 4.2.5 on 2023-10-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zonework", "0003_assessment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="assessment",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
