# Generated by Django 4.2.5 on 2023-10-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zonework", "0004_alter_assessment_options_assessment_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="assessment",
            field=models.BooleanField(
                blank=True,
                choices=[("understand", "Understand"), ("not_yet", "Not Yet")],
                default="not_yet",
                null=True,
            ),
        ),
    ]
