# Generated by Django 4.0.4 on 2023-10-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonework', '0004_alter_assessment_options_assessment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
