# Generated by Django 4.2.3 on 2023-07-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("learning_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningitem",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning_app.student",
            ),
        ),
    ]
