# Generated by Django 4.2.3 on 2023-07-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_app", "0002_alter_learningitem_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningitem",
            name="completed",
            field=models.CharField(max_length=40),
        ),
    ]
