# Generated by Django 4.2.3 on 2023-07-11 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning_app", "0003_alter_learningitem_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningitem",
            name="entry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 11, 14, 56, 9, 565175, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
