# Generated by Django 4.0.4 on 2023-07-17 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0004_learningitem_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningitem',
            name='completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='learningitem',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 10, 30, 46, 249287, tzinfo=utc)),
        ),
    ]
