# Generated by Django 4.2 on 2023-04-10 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zonework_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="entry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 10, 20, 38, 23, 215581, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
