# Generated by Django 4.2 on 2023-04-12 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zonework_app", "0003_alter_item_entry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="entry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 12, 19, 42, 8, 644500, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
