# Generated by Django 4.2 on 2023-04-20 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zonework_app", "0005_alter_item_entry_date_learningitem"),
    ]

    operations = [
        migrations.AlterModelOptions(name="learningitem", options={},),
        migrations.RenameField(
            model_name="learningitem", old_name="in_class", new_name="description",
        ),
        migrations.AlterField(
            model_name="learningitem",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="learningitem",
            name="entry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 20, 11, 31, 35, 662782, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="learningitem",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="student",
            name="class_names",
            field=models.TextField(max_length=200),
        ),
        migrations.DeleteModel(name="Item",),
    ]
