# Generated by Django 4.2 on 2023-04-20 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zonework_app", "0006_alter_learningitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningitem",
            name="entry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 20, 17, 31, 7, 99201, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
