# Generated by Django 4.2 on 2023-04-21 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("zonework_app", "0007_alter_learningitem_entry_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="learningitem", old_name="title", new_name="subject",
        ),
        migrations.RemoveField(model_name="learningitem", name="completed",),
        migrations.AddField(
            model_name="learningitem",
            name="assessment",
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="learningitem",
            name="entry_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
