# Generated by Django 4.2.1 on 2023-05-31 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zonework_app', '0008_rename_title_learningitem_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(verbose_name=False)),
                ('subject', models.CharField(max_length=200)),
                ('assessment', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('entry_date', models.DateTimeField(default=datetime.datetime(2023, 5, 31, 15, 0, 15, 15046, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_names',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='LearningItem',
        ),
        migrations.AddField(
            model_name='item',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonework_app.student'),
        ),
    ]
