# Generated by Django 4.0.4 on 2023-05-31 10:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zonework_app', '0008_rename_title_learningitem_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningitem',
            old_name='description',
            new_name='in_class',
        ),
        migrations.RemoveField(
            model_name='learningitem',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='learningitem',
            name='subject',
        ),
        migrations.AddField(
            model_name='learningitem',
            name='completed',
            field=models.BooleanField(default=False, verbose_name=False),
        ),
        migrations.AddField(
            model_name='learningitem',
            name='title',
            field=models.TextField(default=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='learningitem',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 31, 10, 43, 29, 954165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_names',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(verbose_name=False)),
                ('description', models.TextField(max_length=200)),
                ('entry_date', models.DateTimeField(default=datetime.datetime(2023, 5, 31, 10, 43, 29, 953165, tzinfo=utc))),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonework_app.student')),
            ],
        ),
    ]
