# Generated by Django 4.2.7 on 2023-12-17 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0002_chapter"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Chapter",
            new_name="Video_Chapter",
        ),
    ]
