# Generated by Django 4.2.7 on 2023-12-19 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("zonework", "0003_alter_evaluation_options"),
        ("scraper", "0003_rename_chapter_video_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="video_chapter",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zonework.subject",
            ),
        ),
    ]
