# Generated by Django 4.2.7 on 2023-12-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0004_video_chapter_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="video_chapter",
            name="chapter",
            field=models.TextField(blank=True, null=True),
        ),
    ]
