# Generated by Django 4.2.7 on 2023-12-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0005_video_chapter_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="chapters",
            field=models.TextField(blank=True, null=True),
        ),
    ]
